[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]


[rpc_endpoints]
local="http://127.0.0.1:8545"
sepolia="${SEPOLIA_RPC_URL}"

[etherscan]
sepolia={key="${ETHERSCAN_API_KEY}"}
